// Generated by https://quicktype.io
export interface PokemonSingle {
    id: string;
    name: string;
    imgUrl: string;
}

export interface PokemonMenuList {
    count:    number;
    next:     string | null;
    previous: string | null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}
